# Generated by Django 4.2.10 on 2024-03-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_incomingmaterial_supplier_nameaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmaterial',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='hsn_sac',
            field=models.CharField(default='DEFAULT_VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='incoming_material_inspection',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='invoice_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='material_received_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='received_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incomingmaterial',
            name='supplier_nameaddress',
            field=models.CharField(max_length=100),
        ),
    ]
