# Generated by Django 4.2.10 on 2024-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_requisitionitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='discount',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
