# Generated by Django 4.2.10 on 2024-03-06 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmaterial',
            name='date_of_order',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incomingmaterial',
            name='makes',
            field=models.CharField(default='Some default value', max_length=100),
        ),
        migrations.AddField(
            model_name='incomingmaterial',
            name='model_no',
            field=models.CharField(default='Default Model No.', max_length=100),
        ),
        migrations.AddField(
            model_name='incomingmaterial',
            name='po_no',
            field=models.CharField(default='Default Model No.', max_length=100),
        ),
    ]
