# Generated by Django 4.2.10 on 2024-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_incomingmaterial_date_of_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('make_brand', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('pack_size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('coa_coc_required', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_nameaddress', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=50)),
                ('supplier_nameaddress', models.CharField(max_length=100)),
                ('quotation_no', models.CharField(max_length=50)),
                ('date_of_q', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
