# Generated by Django 4.2.10 on 2024-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_purchase_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_brand', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('po_no', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('pack_size', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coa_coc_required', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
