# Generated by Django 4.2.10 on 2024-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_purchaseitem_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='po_no',
            new_name='quotation_no',
        ),
    ]
