# Generated by Django 4.2.10 on 2024-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_rename_po_no_purchaseitem_quotation_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmaterial',
            name='hsn_sac',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
