# Generated by Django 4.2.10 on 2024-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_incomingmaterial_hsn_sac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
