# Generated by Django 4.2.10 on 2024-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_purchaseitem_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
