# Generated by Django 4.2.10 on 2024-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_vendor_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('makes', models.CharField(default='Default value', max_length=100)),
                ('model_no', models.CharField(default='Default Model No.', max_length=100)),
                ('description', models.TextField()),
                ('grade', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('hsn_sac', models.CharField(default='None', max_length=20)),
                ('remark', models.TextField()),
            ],
        ),
    ]
